### ISSUE TITLE
Duplicated text in "What Is a Font"

### ISSUE THREAD

**Issue by aux0** [fontforge/designwithfontforge.com#110]
The paragraph just below the 1st image on the page and the paragraph just below the 2nd image on the page are nearly identical. Some removing/rewording should be done.

This concerns the English version -- others might have the same problem but I can't read those.

**Comment by marcelommp** [comment]
It's happening here. 

Construction

<image>

Construction refers to the underlying strokes that form a particular glyph. The kind of construction you use is arguably one of the most important questions to think about, because the construction effects so many of the remaining choices, particularly if your design is going to feel somewhat familiar to readers. In the example above, the white line inside the letters indicate the approximate construction suggested by the shape of the letters themselves.

<image>

Construction refers to the structure of the underlying strokes that form a particular glyph. Perhaps you can imagine the glyph’s skeleton. The kind of construction to use is arguably one of the most important questions to think about, because the construction affects so many of the remaining choices, particularly if your design is going to feel somewhat familiar to readers.

**Comment by jrbastien** [comment]
Fixed in latest commit.  Thanks for reporting.
