### ISSUE TITLE
Update screenshots with FontForge 2016.10 theme

### ISSUE THREAD

**Issue by ghost** [fontforge/designwithfontforge.com#137]
![FontForge 2016.10 theme](https://www.opennet.ru/opennews/pics_base/0_1475745944.png)

**Comment by jrbastien** [comment]
I have started working on this issue.  One thing I just noticed is that the eye icons for the layers have been replaced by check boxes.  It must have been a recent change because my French screenshots taken at the beginning of the year do display the eye.

Was that change deliberate?  I can't find the commit where it changed.  I want to make sure this is what we want before taking that many screenshots.

Before:

![layer with eye icons](https://cloud.githubusercontent.com/assets/627071/24249295/12e5f8b8-0fa9-11e7-8e32-7f5436b41718.PNG)

Now:

![layer with checkboxes](https://cloud.githubusercontent.com/assets/627071/24249326/313a04d0-0fa9-11e7-9948-a9fe55766b79.PNG)

@davelab6 , @jtanx , @JoesCat  can you confirm please?

**Comment by jrbastien** [comment]
Guess, who's back tonight?  The eyes!  This look like a bug or a hidden feature ...

**Comment by davelab6** [comment]
LOL

In your images, the language is different - eyes in French, boxes in
English.

I believe the eyes are part of the 'default' theme, and the boxes are
provided as PNGs as part of a theme

**Comment by jrbastien** [comment]
Yes, the eyes was in French to show what I had when I took my screenshot 2 months ago.

Actually, you cannot specify the specific icon for this in the X Resource Editor.  But this issue is fairly easy to reproduce.  Just start a new installation of FF (or clear the theme to reset it to default (Go to Files/Preferences/Generic and delete the resourcefile entry).  You will see that you get check boxes after restart.  Now, change only one thing in the theme (let say Files/X Resource Editor and the font in GGadet).  Save the theme and restart FF. You now get the eyes!

I will report it as a separate bug but I need confirmation of what will be used before taking new screenshot.  Eyes or checkboxes?

**Comment by jrbastien** [comment]
@Symbian9, I believe all is now up-to-date.  Just reopen the issue if you find anything.
