### ISSUE TITLE
German version

### ISSUE THREAD

**Issue by probonopd** [fontforge/designwithfontforge.com#205]
Is there interest in making a German version? I have started here:
https://github.com/probonopd/designwithfontforge.com/tree/de-DE/de-DE

**Comment by JoesCat** [comment]
Hi @probonopd, can you create a pull request on what you have now?
I think it's better to get something started, vs having nothing added.

**Comment by probonopd** [comment]
Well, my guess would be that what I had done is outdated by now?

**Comment by JoesCat** [comment]
Yes, it likely is, but when it comes to translation, if the pages are there, they can be fixed and updated.

As you've noted, it's a pretty big job for just one person to tackle, so let's add it and let others (willing to do so), add their own contributions, small or large.

**Comment by JoesCat** [comment]
Merged and updated what @probonopd had done so far.

It should be easier to (hopefully) continue from this point forwards.

**Comment by JoesCat** [comment]
Closing this issue as done!

NOTE: for anyone interested in helping update German version - this may help you if you are interested in helping fix some of the chapters since there are many pages that have been updated since then and now. Read this first #253 so that you can maintain a sync with the main trunk.
