### ISSUE TITLE
Contributing page/section

### ISSUE THREAD

**Issue by garyritchie** [fontforge/designwithfontforge.com#34]
I think it would be valuable to have a page for contributors to the "book" to follow. It should outline:
1. specifications for images (figures), 
2. style for said figures, 
3. what to do with the source files so that others can more easily edit and build upon the work. 

Any other items?

**Comment by aryelgois** [comment]
The item 3 would be very helpful for translators

**Comment by JoesCat** [comment]
Wishlist with nothing done since 2013.
Out of experience doing contributions and merging PRs, the more you ask of volunteers, the less you will get people volunteering. It's usually best to let people volunteer what they can, to their best ability, and avoid putting-up to many rules.

Closing issue.
