### ISSUE TITLE
language filter for index page

### ISSUE THREAD

**Issue by zerng07** [fontforge/designwithfontforge.com#49]
Now we have multilanguages since zh-TW contents added. 
Index will list all pages including zh-TW pages.

I think that we can use custum lang variables in front matter to filter what the lang we would like to be listed in Index. For example, "zh_TW: true" for zh-TW pages (pages under zh-TW directory) while "en_US:true" for en-US pages (pages under en-US pages).

Then we add if-expression to select zh-TW pages or en-US pages,

 {% for weight in (1..100) %}
   {% for p in site.pages %}
-    {% if p.zh_TW == true %}
  
   {% if p.weight > 0 %}
   {% if p.weight == weight %}
   ...
-     {% endif %}

or
-    {% if p.en_US == true %}

Is this solution acceptable for you guys? Any feedback welcome. ;)

**Comment by JoesCat** [comment]
On October 7, 2014 06:10:47 AM zerng07 wrote:

> Is this solution acceptable for you guys? Any feedback welcome. ;)

zw_TW... or zw-TW,
I think you/we need to think in lower-case letters for website URLs. It was 
a default on older websites and maybe worth keeping to that default to 
simplify access and avoid problems in accessing pages.
http://www.google.ca/search?q=website+url+uppercase+lowercase

...having said that, we should renaming some pages as all lower-case.

**Comment by zerng07** [comment]
As a long term l10n contributor, here is as far as I know about zh_TW vs. zh-TW.
- zh_TW is mostly used within applications with gettext i18n support. GNOME, KDE and other FLOSS programs use "zh_TW" as internal lang code for Chinese (Taiwan) or Chinese (Traditional).
- zh-TW is mostly used within web areas. Firefox uses zh-TW as the lang code for Chinese (Taiwan) or Chinese (Traditional) in 'about:config'. Besides zh-TW, zh-Hant is used in Wikipedia and equal to zh-TW.

"zh" stands for Chinese. 
"TW" for Taiwan region.
"CN" for China region.
"Hant" for traditional Han characters.
"Hans" for simplified Han characters.
zh-TW == zh-Hant; zh-CN == zh-Hans

**Comment by JoesCat** [comment]
What I was thinking about, was the URLs.
So, instead of subdirectory zh-TW, it should be renamed zh-tw, so that when 
someone specifies a "webpage", the webpage is all lower-case letters.

URL www.mywebsite/zh-tw/index.html

This also needs to be applied to the other webpages as well, so right now 
it is incorrectly setup as:
URL www.mywebsite/en-US/Capital_Letters.md

and should be more correctly labelled as:

URL www.mywebsite/en-us/capital_letters.md

**Comment by zerng07** [comment]
Yeah, that makes sense.

**Comment by zerng07** [comment]
Any ideas on this language filter issue?

Or I will add "en_US: true" custom variable to front matter of pages in en-US directory. Then to edit index.md to select en_US contents.

**Comment by JoesCat** [comment]
On October 8, 2014 05:54:33 AM zerng07 wrote:

> Any ideas on this language filter issue?
> 
> Or I will add "en_US: true" custom variable to front matter of pages in
> en-US directory. Then to edit index.md to select en_US contents.

Close, but we need to have a "default" language for the language choices we 
have not covered, so you can't filter true on en-US, but we can make it 
default instead (to cover all other languages).

Here is an example for the FontForge open desktop:
https://github.com/fontforge/fontforge/blob/master/desktop/fontforge.appdata.xml
You will notice the en-US is default instead of filtered.

If you want to add a zh-TW translated description here, we just need to add 
your translation.

**Comment by zerng07** [comment]
Sorry that I don't really get what you mean... 

What I am talking about is to filter the right content listed in "index".
http://designwithfontforge.com/en-US/index.html

You can see there is one Chinese (Taiwan) translated version of "introduction" listed in index for en-US lang besides English ones.

So do you mean that it is not appropriate to add something like "en_US: true" because en_US is default lang (our primary language)? Em... that is right. Maybe we should come out some other methods to do this multilang-selecting job.

**Comment by JoesCat** [comment]
On October 8, 2014 08:13:59 AM zerng07 wrote:

> Sorry that I don't really get what you mean...
> 
> What I am talking about is to filter the right content listed in
> "index". http://designwithfontforge.com/en-US/index.html
> 
> You can see there is one Chinese (Taiwan) translated version of
> "introduction" listed in index for en-US lang besides English ones.
> 
> So do you mean that it is not appropriate to add something like "en_US:
> true" because en_US is default lang (our primary language)? Em... that
> is right. Maybe we should come out some methods to do this
> multilang-selecting job.

Instead of this:
if en-US then do this
if zh-TW then do this
if uk then do this
if pt then do this

This method above has a problem if someone has de or fr or another language 
that we did not think of including, or even subregions making it more 
complicated. For example, my browsers are set for en-CA and en

you need to think more of "how do I have a default?
if zh-TW then do this
else if uk then do this
else if pt then do this
else do this (default language)

so, looking at your example up above of:
{% if p.en_US == true %}
needs to be changed to handle everything else

**Comment by JoesCat** [comment]
> Maybe we should come out some methods to do this
> multilang-selecting job.

Yes, we need another method that has a default for unlisted languages.

**Comment by adrientetar** [comment]
There is the HTML hreflang for language-based switching. Otherwise, we should just let the user choose, there are subfolders for each language anyway so you can link to the language you want etc.

**Comment by zerng07** [comment]
I mean this lang-specific custom variable in Front Matter is used like a tag to mark the language of the page. 

Each lang directory such as en-US and zh-TW both includes a index.md and it lists "All" exisiting pages. 
I studied the documentation on variables on http://jekyllrb.com/docs/variables/ and find there is no easy way to filter pages under directory, thus I came out this method. It is used for selecting right content of right language for the index.md under specific lang directory.

It could be changed into "lang: zh_TW" instead of "zh_TW: true", and then use 'p.lang == "zh_TW"' to select the pages under zh_TW directory. 

We could later create a navigation menu like the one in fontforge.gitub.io to switch to the corresponding index.md under lang directory for each supported language.

Pardon me that I do not understand why this method could affect unlisted languages and needs a default. :(

If this method is not appropriate, maybe we should keep this pending until we figure out one. And I will keep focus on translating the pages for zh_TW translation.

**Comment by JoesCat** [comment]
> If this method is not appropriate, maybe we should keep this pending
> until we figure out one. And I will keep focus on translating the pages
> for zh_TW translation.

Don't worry too much about it. Focus on the main task of "translating".
Leave this as a problem to solve later. Even if it doesn't get solved, at 
least the main thing you wanted to do gets done. :-)

**Comment by zerng07** [comment]
OK! Thanks for your advice. :)

**Comment by zerng07** [comment]
JohnWang has created a language switch on main page. Merged with #61 .

Comments are welcome. If accepted, we can close this issue.
